version: '3.5'

services:
  tmi-receiver:
    image: microtwitch/tmi-dispatcher:latest
    container_name: tmi-dispatcher
    ports:
      - "7070:7070"

networks:
  default:
    external: true
    name: tmi
