version: '3.5'

services:
  tmi-receiver:
    image: microtwitch/tmi-dispatcher:latest
    container_name: tmi-dispatcher
    environment:
      - GRPC_SERVER_PORT=7070


networks:
  default:
    external: true
    name: tmi
